title: Databasernas grunder
subtitle: v√•r 2026
lang: fi # Or fi for Finnish
baseurl: "/var-2026"
url: "https://tikape.mooc.fi"
# Uncomment to change the theme color:
# theme-color: '#60a6ec'

remote_theme: ollpu/jekyll-course-theme@v2

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # Uncomment for Finnish quotes:
  # smart_quotes: rsquo,rsquo,rdquo,rdquo

permalink: /:title/

small_code_font: true

# If you want a collection of pages for course material:
collections:
  # In Finnish you might want to write e.g. "materiaali:" instead.
  material:
    output: true
    permalink: /:title/

# Uncomment to hide the section submenus in navigation
# for pages other than the current one:
# hide_other_section_menus: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
